version: "3.8"

services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable_freqai
    container_name: freqtrade-bot
    restart: unless-stopped
    volumes:
      - ./user_data:/freqtrade/user_data
      - ./config:/freqtrade/config
      - ./strategies:/freqtrade/user_data/strategies
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      trade
      --config /freqtrade/config/${FT_CONFIG:-config-dryrun.json}
      --strategy ${FT_STRATEGY:-EmaCrossRsi}
